# Welcome to Serverless!
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: poc-pdf

custom:
  bucket: poc-pdf-files

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  region: eu-west-1

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /
          method: post
          cors: true
    layers:
      - arn:aws:lambda:eu-west-1:764866452798:layer:chrome-aws-lambda:8
    environment:
      BUCKET: ${self:custom.bucket}
    timeout: 30
